name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: docker
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - uses: https://github.com/browser-actions/setup-chrome@v1
      id: setup-chrome
      with:
        install-chromedriver: true

    - name: Test
      env:
        CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}   # Set Chrome binary path
      run: xvfb-run --auto-servernum go test -race -covermode atomic -coverpkg=./internal/...,./cmd/... -coverprofile=covprof -v ./...

    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: goveralls -coverprofile=covprof -service=github

